"""empty message

Revision ID: 313db0676132
Revises: 
Create Date: 2024-11-12 11:06:12.918622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313db0676132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=100), nullable=True),
    sa.Column('teacher', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('timeOff', sa.String(), nullable=True),
    sa.Column('allowSecondLesson', sa.Boolean(), nullable=True),
    sa.Column('preparation', sa.String(), nullable=True),
    sa.Column('lunch', sa.String(), nullable=True),
    sa.Column('maxQuestionMarked', sa.String(), nullable=True),
    sa.Column('specificTimeEveryDay', sa.String(), nullable=True),
    sa.Column('lessonsStartPeriod', sa.String(), nullable=True),
    sa.Column('lessonsEndPeriod', sa.String(), nullable=True),
    sa.Column('lessonsPerDayInterval', sa.String(), nullable=True),
    sa.Column('daysWithLessons', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('timeOff', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('combinedWith', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('start', sa.String(), nullable=False),
    sa.Column('end', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('print', sa.Boolean(), nullable=True),
    sa.Column('bell', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.String(), nullable=True),
    sa.Column('classes', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('condition_order', sa.String(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolName', sa.String(length=200), nullable=True),
    sa.Column('academicYear', sa.String(), nullable=True),
    sa.Column('registrationName', sa.String(), nullable=True),
    sa.Column('periodsPerDay', sa.Integer(), nullable=True),
    sa.Column('zeroPeriods', sa.Boolean(), nullable=True),
    sa.Column('allowZeroPeriodLessons', sa.Boolean(), nullable=True),
    sa.Column('numberOfDays', sa.Integer(), nullable=True),
    sa.Column('weekend', sa.String(), nullable=True),
    sa.Column('multiTerm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('timeOff', sa.String(length=50), nullable=True),
    sa.Column('distribution', sa.String(), nullable=True),
    sa.Column('homeworkPreparationRequired', sa.String(), nullable=True),
    sa.Column('maxOnTheQuestionMarked', sa.String(), nullable=True),
    sa.Column('maxOfOnePerDay', sa.Boolean(), nullable=True),
    sa.Column('doubleLessons', sa.String(), nullable=True),
    sa.Column('classrooms', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('timeOff', sa.String(), nullable=True),
    sa.Column('classTeacher', sa.Boolean(), nullable=True),
    sa.Column('Qualification', sa.String(length=100), nullable=True),
    sa.Column('maxWindows', sa.Integer(), nullable=True),
    sa.Column('daysTaught', sa.Integer(), nullable=True),
    sa.Column('lessonIntervals', sa.String(), nullable=True),
    sa.Column('maxQuestionsMarked', sa.Integer(), nullable=True),
    sa.Column('maxWindowsPerDay', sa.Integer(), nullable=True),
    sa.Column('avoidThreeConsecutiveFreePeriods', sa.Boolean(), nullable=True),
    sa.Column('avoidTwoConsecutiveFreePeriods', sa.Boolean(), nullable=True),
    sa.Column('contract', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generateDifferentTimetables', sa.Boolean(), nullable=False),
    sa.Column('checkExhaustion', sa.Boolean(), nullable=False),
    sa.Column('maxExhaustion', sa.Integer(), nullable=True),
    sa.Column('checkWindowsOfTeachers', sa.Boolean(), nullable=False),
    sa.Column('maxWindows', sa.Integer(), nullable=True),
    sa.Column('allowZeroPeriod', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('startTime', sa.String(), nullable=True),
    sa.Column('endTime', sa.String(), nullable=True),
    sa.Column('classroom', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('className', sa.Integer(), nullable=False),
    sa.Column('rollNumber', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['className'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rollNumber')
    )
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.Column('day', sa.String(length=200), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetables')
    op.drop_table('students')
    op.drop_table('exams')
    op.drop_table('activities')
    op.drop_table('timetable_parameters')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('settings')
    op.drop_table('reports')
    op.drop_table('relations')
    op.drop_table('periods')
    op.drop_table('items')
    op.drop_table('days')
    op.drop_table('custom_fields')
    op.drop_table('classrooms')
    op.drop_table('classes')
    # ### end Alembic commands ###
